### ISSUE TITLE
Not Working in IE 11

### ISSUE THREAD

**Issue by joshiabk** [Microsoft/angular2-slickgrid#17]
Hi,

The function **getColumnCssRules** under **slick.grid.js**   not able to fill the object **_columnCssRulesL[idx]_** and **_columnCssRulesL[idx]_** so returning **left** and **right** as a **_undefined_**

It is only happening for **IE**. **IE** is throwing the below error.

```
ERROR TypeError: Unable to get property 'style' of undefined or null reference
   "ERROR"
   {
      [functions]: ,
      __proto__: { },
      description: "Unable to get property 'style' of undefined or null reference",
      message: "Unable to get property 'style' of undefined or null reference",
      name: "TypeError",
      ngDebugContext: { },
      number: -2146823281,
      stack: "TypeError: Unable to get property 'style' of undefined or null reference
   at applyColumnWidths (http://localhost:8080/node_modules/slickgrid/slick.grid.js:1302:9)
   at updateCanvasWidth (http://localhost:8080/node_modules/slickgrid/slick.grid.js:517:9)
   at updateRowCount (http://localhost:8080/node_modules/slickgrid/slick.grid.js:2054:7)
   at resizeCanvas (http://localhost:8080/node_modules/slickgrid/slick.grid.js:1967:7)
   at finishInitialization (http://localhost:8080/node_modules/slickgrid/slick.grid.js:361:9)
   at init (http://localhost:8080/node_modules/slickgrid/slick.grid.js:328:9)
   at SlickGrid (http://localhost:8080/node_modules/slickgrid/slick.grid.js:4039:5)
   at SlickGrid.prototype.initGrid (eval code:406:9)
   at SlickGrid.prototype.ngOnChanges (eval code:212:17)
   at checkAndUpdateDirectiveInline (eval code:10865:9)"
   }

```

**Comment by kevcunnane** [comment]
@anthonydresser is this in the core SlickGrid library? If so, it's likely best for @joshiabk to open the issue there, correct?

**Comment by anthonydresser** [comment]
The slickgrid github page only specifies it doesn't support ie6. I have seen this problem on Firefox as well. but this does seem to be a underlying lib issue not a wrapper issue. It might have something to do with the small amount of changes that have been made to the lib.

**Comment by joshiabk** [comment]
@anthonydresser I have seen this issue on IE 11. I am trying to find out the things so it can work. In you lib under slick.grid.js there is one function which is es6 and breaking in IE.

`"getColumnWidths": function() { return columns.map(c => c.width); },` on line 4024.
I have changed it to `"getColumnWidths": function() { return columns.map(function(c){return c.width;}); },`.

**Comment by anthonydresser** [comment]
@joshiabk That's interesting ie11 does not support arrow functions. I'll make sure to go through the rest of the lib and verify theres no other arrow functions elsewhere.

**Comment by joshiabk** [comment]
@anthonydresser  I just clone of your repo and test the same and unfortunately it's giving the same error which I mention first. Not working on IE 11 as well as on edge. Chrome is working perfectly. I am looking into it. If i'll found something i'll let you know and push the changes.

**Comment by ghiscoding** [comment]
Just starting to look at your repo, I used SlickGrid for a long time until I've done AngularJS then we used UI-Grid. All that to say, you're most probably missing Polyfill, IE11 doesn't support much (11%) of ES6, however Edge does support fat arrow, strangely Edge fails as well.

**Comment by ghiscoding** [comment]
There you go, the issue is in your [tsconfig.json](https://github.com/Microsoft/angular2-slickgrid/blob/master/tsconfig.json#L7), you set the target to be `es6` and IE doesn't support ES6 directly so it fails, if I copy over the `tsconfig.json` of `Angular-CLI`, I got IE11 to work however Edge still isn't working and I don't know why.

So anyhow, using this `tsconfig.json` will make IE11 to work:
```javascript
{
    "compileOnSave": false,
    "compilerOptions": {
      "outDir": "./dist/out-tsc",
      "baseUrl": "./",
      "rootDir": "./",
      "sourceMap": true,
      "declaration": false,
      "moduleResolution": "node",
      "emitDecoratorMetadata": true,
      "experimentalDecorators": true,
      "target": "es5",
      "typeRoots": [
        "node_modules/@types"
      ],
      "lib": [
        "es2016",
        "dom"
      ]
    }
  }
```
This file is a lot different compared to yours though, and I'm not familiar with the `tsconfig.json` entire settings. I wanted to see if the target was the issue and it is.
